template = """
` 1 2 3 4 5 6 7 8 9 0 - =
⇥ q w e r t y u i o p [ ] \\
  a s d f g h j k l ; ' ↵
⇧  z x c v b n m , . /  ⇪
          ︺  
"""
hands = """
l l l l l l r r r r r r r
l l l l l l r r r r r r r r
  l l l l l r r r r r r r
l  l l l l l r r r r r  r
            r
"""
fingers = """
1 1 2 3 4 4 4 4 3 2 2 1 1
1 1 2 3 4 4 4 4 3 2 1 1 1 1
  1 2 3 4 4 4 4 3 2 1 1 1
1  1 2 3 4 4 4 4 3 2 1  1
            5
"""
efforts = """
17 14 08 08 13 16 23 19 09 08 07 15 17
15 06 02 01 06 11 14 09 01 01 07 09 13 18
   01 00 00 00 07 07 00 00 00 01 05 11
05  07 08 10 06 10 04 02 05 05 03   12
                00
"""
# to play later with, another model lifted of the internet
# https://colemakmods.github.io/mod-dh/model.html
# efforts: "
# 55 46 40 34 29 29 35 29 29 30 35 42 51
# 42 30 25 21 23 26 34 22 20 24 30 36 47 56
#    16 13 11 10 29 29 10 11 13 16 34 48
# 46  27 24 18 22 37 22 18 24 27 33   46
#                 00
# ",
rolling_pairs = """
we wf   er ew   re   io    oi oj
as af   sd se sf  df  fe fw fs fa   ji jl j; jo   kj  lk li lj lm  ;l ;j
vd vw vs va    mk ml m; mo mi //l
"""
bad_starters = """
q    r t y u     p [ ] \\
   d   g h   k    '
 z x c  b n   , . /
"""