geometry = "US-PC"

mutate_every = 10 # adds a mutation with every batch

progress_window_size = 100

[population]
size = 60
steps = 4 # mutation rounds per population
elites = 10 # percentile of elites (set to 0 to switch off)
symbols = false # mutate punctuation idependently

[selection]
rank_space_cut_off = 95 # percent
diversity_bias = 0.25 # coefficient 0..1

[weights]
effort = 4      # total effort
overheads = 1   # total overheads
awkwardness = 1 # bad startes
rollingness = 2 # combos
fitness = 8     # usage balance