geometry = "US-PC"
population_size = 50
mutate_every = 10 # adds a mutation with every batch
mutate_symbols = false

progress_window_size = 100

[selection]
rank_space_cut_off = 95 # percent
diversity_bias = 0.25 # coefficient 0..1

[elites]
portion = 5
inject = true

[weights]
effort = 1      # total effort
overheads = 1   # total overheads
awkwardness = 1 # bad startes
rollingness = 1 # combos
fitness = 1     # usage balance